// Conversation Experience kit. Guidance text comes from src/pages/ConversationExperiencePage.tsx (CHAPTERS, METRICS).
const L = require('./lib');
const { esc, ex, fid, area, val, ov, card, row, sec, table, check, tool } = L;
L.CFG.sub = 'Conversation Experience Playbook';
L.setNS('NorthStar GmbH · Careers Assistant: a conversational front door for candidates', 'NorthStar hires food technologists, plant operators and office staff across its sites worldwide. The Careers Assistant answers candidates in chat and voice: finding roles, checking application status, scheduling interviews and handing over to a recruiter. Figures are illustrative.');
const P = (arr) => `<div class="card list">${arr.map(p => `<p class="prin">${esc(p)}</p>`).join('')}</div>`;

tool('start', 'Start here', { ov: 'Conversation Experience kit', title: 'Design conversations people trust', sub: 'A working kit for conversational, assistant-driven and agentic experiences. Each tool turns one chapter of the playbook into a template you can fill in, with a worked example.', example: false }, () =>
  sec('How the kit fits together', 'Work in order. Intent comes before interface; measurement closes the loop.', `<ol class="flow">${[['intent', 'Intent Map', 'Map what users mean, not just what they say.'], ['response', 'Response Architecture', 'Define structure and tone by interaction type.'], ['multiturn', 'Memory & Repair', 'Decide what the system remembers and how it recovers.'], ['trust', 'Trust & Safety', 'Design confidence, "I don\'t know", sources and guardrails.'], ['agentic', 'Agentic & Multimodal', 'Prepare for systems that act, and for voice and image.'], ['measure', 'Measurement Scorecard', 'Track the six metrics that matter for conversation.']].map(([id, n, d], i) => `<li><a href="#${id}"><span class="n">${i + 1}</span><b>${n}</b><span>${d}</span></a></li>`).join('')}</ol>`)
  + sec('Measure conversations differently', 'Task completion, containment rate and trust signals, not page views.', row([['Task completion', '>75% for primary flows'], ['Containment', '>60% is strong for enterprise'], ['Trust score', '>7/10 after 3 sessions']].map(([a, b]) => `<div class="card">${ov(a)}<p class="strong">${b}</p></div>`), 220))
  + sec('Still to come from Amit', null, `<div class="card"><p class="strong">The full Engaze design methodology and the case study breakdowns are promised in the playbook but are not in this kit yet.</p></div>`));

tool('intent', 'Intent Map', { ov: 'Tool 1 · Intent Design', title: 'Intent Map', sub: 'Designing for what users mean, not what they say. Map the full universe of what users are trying to accomplish before you design a single message.', anatomy: ['Define intent categories before designing dialog flows.', '45 minutes, with the engineers training the model', 'Response Architecture.'] }, () =>
  sec('Principles', null, P(['Define intent categories before designing dialog flows', 'Map the gap between what users say and what they mean — this gap is your design opportunity', 'Build intent models collaboratively with the engineers training the AI model', 'Test with real utterances from real users, not hypothetical ones from a workshop']))
  + sec('Intent map', 'One row per intent. Use real utterances from transcripts, search logs or support tickets.', table(['Intent', 'What users say', 'What they mean', 'Context and emotional state', 'Constraints', 'Priority'], 6, [
    ['Find a role', '"any jobs near Poznań?" · "food science jobs"', 'Show roles that match my skills near where I live', 'Browsing, low commitment, often on mobile', 'Roles change weekly; location names vary by language', 'High'],
    ['Check application status', '"did you get my CV?" · "any news?"', 'Reassure me it arrived and tell me when I will hear back', 'Anxious, sometimes days after applying', 'Status lives in the applicant tracking system', 'High'],
    ['Reschedule interview', '"can\'t make Tuesday"', 'Move my interview without losing my place', 'Stressed, time-sensitive', 'Panel calendars; time zones', 'High'],
    ['Ask about benefits or relocation', '"do you help with moving?"', 'Is this job realistic for my life?', 'Deciding whether to apply', 'Policy differs by country and site', 'Medium'],
    ['Withdraw application', '"I took another offer"', 'Close this cleanly and politely', 'Relieved or awkward', 'Must update the ATS and notify the recruiter', 'Medium'],
    ['Talk to a person', '"recruiter please" · "human"', 'This is too important or too unclear for a bot', 'Frustrated or high-stakes', 'Recruiter hours; handover with context', 'High']], [150, null, null, null, null, 80])));

tool('response', 'Response Architecture', { ov: 'Tool 2 · Prompt & Response Systems', title: 'Response Architecture', sub: 'The language layer. Define how information is structured, sequenced and voiced, across every interaction type and emotional register.', anatomy: ['Give every response type a structure and a tone before writing copy.', '60 minutes', 'Memory & Repair.'] }, () =>
  sec('Principles', null, P(['Define response architecture by interaction type, not by topic', 'Informational, transactional, clarifying, and escalating responses each have a different optimal structure', 'Failure states deserve as much design attention as success states — more, actually', 'Tone calibration is a design decision, not a copywriting afterthought']))
  + sec('Architecture by interaction type', null, table(['Interaction type', 'Structure', 'Tone', 'Example response', 'Avoid'], 0, [
    ['Informational', 'Answer first, then one detail, then one next step', 'Clear, warm', '"Yes, we have 3 food technologist roles near Poznań. The closest is at our Września plant. Want to see it?"', 'Lists of every field from the database'],
    ['Transactional', 'Confirm what will happen, do it, confirm it is done', 'Precise, calm', '"Moving your interview to Thursday 16 Oct, 10:00 CET. Done. You will get a new calendar invite."', 'Asking for details already known'],
    ['Clarifying', 'Offer the most likely meaning as a choice', 'Helpful, brief', '"Do you mean the Food Technologist role in Poznań, or Quality Lead in Hamburg?"', 'Open "please rephrase" questions'],
    ['Escalating', 'Say why, say who, say when, carry context', 'Respectful, honest', '"Salary questions go to your recruiter, Anna. I have passed on your question; she replies within 2 working days."', 'Dead ends or silent handovers'],
    ['Failure', 'Own it, offer a path, keep the context', 'Plain, no blame', '"I could not find your application with that email. Try the email you applied with, or I can connect you to a recruiter."', '"Error 404" or blaming the user']], [150, null, 120, null, null], ['Informational', 'Transactional', 'Clarifying', 'Escalating', 'Failure'].map(t => [t, '', '', '', '']))));

tool('multiturn', 'Memory & Repair', { ov: 'Tool 3 · Multi-Turn Flows', title: 'Memory & Repair', sub: 'Multi-turn design is about memory and repair: knowing what to carry forward and knowing what to do when things break.', anatomy: ['Decide what the system remembers, for how long, and how it recovers.', '45 minutes', 'Trust & Safety.'] }, () =>
  sec('Principles', null, P(['Context window design: what does the system remember and for how long?', 'Design explicit repair strategies — what happens when the system misunderstands?', "Progressive disclosure applies to conversations too: don't surface all capabilities at once", 'Session continuity across return visits is a retention decision, not just a UX convenience']))
  + sec('Context window', null, table(['What is remembered', 'For how long', 'Why', 'User can'], 4, [['Role the candidate is discussing', 'This session', 'Avoid asking again in every turn', 'Change it any time'], ['Application reference', 'Until the application closes', 'Status questions are answered instantly on return', 'Ask to forget it'], ['Preferred language and location', '90 days', 'Faster, relevant role suggestions', 'Clear in settings'], ['Interview details', 'Until the interview has passed', 'Reschedule without re-identifying', 'Cancel or move']]))
  + sec('Repair strategies', null, table(['Misunderstanding', 'How we detect it', 'Repair move', 'If repair fails'], 4, [['Wrong role or location', 'User says "no" or repeats with changes', 'Offer the two closest matches as choices', 'Show a search form with filters'], ['Ambiguous date', '"next Tuesday" across a month boundary', 'Confirm the full date back', 'Show a date picker'], ['Out of scope (salary negotiation)', 'Intent classifier: negotiation', 'Say it is a recruiter topic and offer handover', 'Create a recruiter task'], ['Repeated failure', 'Two failed repairs in a row', 'Apologise once and offer a person', 'Handover with transcript']]))
  + sec('Progressive disclosure', 'Introduce capabilities in the order people need them.', row([['First visit', 'Find roles, apply'], ['After applying', 'Status, documents'], ['After invitation', 'Scheduling, directions, what to bring']].map(([a, b]) => card(a, null, b, 48)), 220)));

tool('trust', 'Trust & Safety', { ov: 'Tool 4 · Trust & Safety', title: 'Trust & Safety', sub: 'Trust is built by being honest about uncertainty, recovering gracefully from errors, and never pretending to know more than the system knows.', anatomy: ['Make the system trustworthy without making it useless.', '45 minutes', 'Agentic & Multimodal.'] }, () =>
  sec('Principles', null, P(['Confidence surfacing: high-confidence and low-confidence responses should look different', 'Design the "I don\'t know" response with as much care as the answer', 'Source attribution builds trust — anonymous information is unverifiable information', 'Safety guardrails should be designed to be invisible when not triggered, and clear when they are']))
  + sec('Confidence surfacing', null, row([['High confidence', 'State it plainly and act.', '"Your interview is confirmed for Thursday 16 Oct, 10:00 CET."'], ['Medium confidence', 'Show the reasoning and ask.', '"I think you mean the Food Technologist role in Poznań. Is that right?"'], ['Low confidence', 'Say so and route it.', '"I am not sure about relocation support for that site. I have asked a recruiter, who replies within 2 working days."']].map(([a, b, c]) => card(a, b, c, 70)), 240))
  + sec('"I don\'t know" response', null, card('Our version', 'What the system says when it cannot answer, and what it offers instead.', '"I don\'t have that information. Here is who does: your recruiter, Anna. Want me to send her your question?"', 70))
  + sec('Sources and guardrails', null, table(['Topic', 'Source shown to user', 'Guardrail', 'What the user sees when triggered'], 4, [['Benefits and relocation', 'Country policy page, with date', 'Answer only from the current policy', 'Link to the policy and a recruiter offer'], ['Other candidates', 'None', 'Never discuss other applicants', '"I can only talk about your own application."'], ['Hiring outcome', 'None', 'Never predict or promise a decision', '"Decisions come from the hiring team. I can tell you the next step."'], ['Being an AI', 'Shown at the start of every chat', 'Always disclose that this is an AI assistant', '"I am NorthStar\'s AI assistant. You can ask for a person at any time."']])));

tool('agentic', 'Agentic & Multimodal', { ov: 'Tool 5 · The Future of Conversational UX', title: 'Agentic & Multimodal', sub: 'Systems that do not just respond but act, escalate and operate on behalf of users. The relationship between human intent and system action is becoming the product.', anatomy: ['Check readiness before the assistant starts acting on its own.', '30 minutes', 'Measurement Scorecard.'] }, () => {
  const items = ['Every action the assistant can take on its own is listed, with who can undo it.', 'Actions that need approval show what will happen before it happens.', 'Escalations carry the full context to the person who receives them.', 'The same intent model is used for text, voice and image input.', 'There is a clear way to ask "what did you do on my behalf?"'];
  return sec('Principles', null, P(['Agentic systems require oversight design, not just interaction design', 'Multimodal conversations (voice, text, image) require consistent intent models across modalities', "The collapse of the screen as primary canvas is not a threat to UX designers — it's the biggest opportunity", 'Measure conversational experiences differently: task completion, containment rate, and trust signals — not page views']))
    + sec('Oversight readiness', null, `<div class="card list">${items.map((q, i) => check(q, i !== 4)).join('')}</div>` + (ex() ? card('Gap found', null, 'No activity history yet. Candidates cannot see that the assistant moved their interview. Add an "activity" view before launch.') : ''))
    + sec('One intent, every modality', null, table(['Intent', 'Text', 'Voice', 'Image'], 3, [['Reschedule interview', 'Two suggested slots as buttons', 'Reads two slots, accepts "the first one"', 'Not used'], ['Find a role', 'Role cards with location', 'Reads the top 3 roles only', 'Photo of a job ad → finds the role'], ['Upload documents', 'File upload', 'Sends a secure upload link by SMS', 'Photo of a certificate, read and confirmed']]));
});

const M = [['Task Completion Rate', 'Percentage of user intents successfully resolved without human escalation.', '>75% for primary flows', 'Resolved intents / Total intents × 100', '78%', 'ok'], ['Containment Rate', 'Percentage of conversations handled entirely by the AI without escalation to a human agent.', '>60% is strong for enterprise', 'AI-only conversations / Total conversations × 100', '64%', 'ok'], ['Resolution Quality Score', 'User-rated quality of responses — combining accuracy, tone, and helpfulness.', '>4.0/5.0 in usability testing', 'Post-conversation survey (5-point scale)', '4.1', 'ok'], ['Escalation Rate', 'Percentage of conversations that require human handoff — a signal of AI capability gaps.', '<25% for mature systems', 'Human-escalated conversations / Total × 100', '22%', 'ok'], ['Repair Success Rate', 'When the system misunderstands, how often does the repair strategy work?', '>80% recovery on first repair', 'Successful repairs / Triggered repairs × 100', '71%', 'gap'], ['Trust Score', 'Composite measure of user confidence in system accuracy, honesty, and reliability.', '>7/10 after 3 sessions', 'Multi-item trust scale (post-session)', '6.8', 'gap']];
tool('measure', 'Measurement Scorecard', { ov: 'Tool 6 · Measurement', title: 'Measurement Scorecard', sub: 'Measure conversational experiences differently: task completion, containment rate and trust signals, not page views.', anatomy: ['Track whether the assistant is working, and where to improve next.', 'Monthly', 'The next iteration of the Intent Map and repair strategies.'] }, () =>
  sec('Scorecard', null, `<div class="tw"><table><thead><tr><th style="width:190px">Metric</th><th>Definition</th><th style="width:150px">Target</th><th>Formula</th><th style="width:110px">Current</th><th style="width:100px">Status</th></tr></thead><tbody>${M.map(m => `<tr><td>${esc(m[0])}</td><td>${esc(m[1])}</td><td>${esc(m[2])}</td><td>${esc(m[3])}</td><td>${ex() ? `<b>${m[4]}</b>` : `<textarea class="cell" id="${fid()}" data-save rows="1" aria-label="Current"></textarea>`}</td><td>${ex() ? `<span class="st ${m[5]}">${m[5] === 'ok' ? 'On target' : 'Below target'}</span>` : `<textarea class="cell" id="${fid()}" data-save rows="1" aria-label="Status"></textarea>`}</td></tr>`).join('')}</tbody></table></div>`)
  + (ex() ? sec('What to do next', null, row([card('Repair success 71%', null, 'Most failed repairs are ambiguous dates. Replace open questions with a full-date confirmation and a date picker.'), card('Trust score 6.8', null, 'Candidates who were escalated without a named recruiter scored lowest. Always name the person and the reply time.')], 300)) : ''));

console.log(L.page('/home/claude/kits/conversation-experience-kit.html', 'Conversation Experience Kit', '', 'cx'));
